# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fotos da pam
email: fotosdapam@yahoo.com.br
description: > # this means to ignore newlines until "baseurl:"
  Fotos da pam é o site da fotografa Pammela Lisboa, que realiza cobertura
  fotográfica de festas e ensaios fotográficos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fotosdapam.com.br" # the base hostname & protocol for your site, e.g. http://example.com
logo: "assets/imgs/min/avatar.jpg"
twitter:
  username: fotosdapam
facebook:
  admins: pammlisboa
social:
  name: Pammela Lisboa
  links:
    - https://www.facebook.com/fotosdapam/?fref=ts
    - https://www.facebook.com/pammlisboa?fref=ts
    - https://www.instagram.com/fotosdapam/

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - node_modules
